---
name: pemo
description: PEMO application
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.3
  flutter_facebook_auth: ^5.0.7
  firebase_auth: ^4.2.5

  provider: ^6.0.5
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  permission_handler: ^10.2.0
  http: ^0.13.5
  intl: ^0.17.0

  connectivity_plus: ^2.3.9
  intl_phone_number_input: ^0.7.3
  font_awesome_flutter: ^10.3.0
  image_picker: ^0.8.6+1
  another_flushbar: ^1.12.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
